version: 2.0

# Define the environment for the build
environment:
  vars:
    NODE_VERSION: '16.x'  # Specify the Node.js version
    NPM_VERSION: 'latest'  # Optionally specify the NPM version

# Define the workflows
workflows:
  ios:
    name: Build and Deploy iOS App
    max_build_duration: 60  # Max build duration in minutes

    # Define the configuration for the build
   

    # Define the build steps
    scripts:
      # Install dependencies
      - name: Install Dependencies
        script: |
          npm install -g ionic cordova
          npm install

      # Build the Ionic project
      - name: Build Ionic Project
        script: |
          ionic cap build ios 
      # Prepare the iOS platform and build
      - name: Prepare iOS Platform and Build
        script: |
          npx cap sync ios
          npx cap build ios

      # Archive the app and export IPA
      - name: Archive and Export IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -archivePath build/App.xcarchive archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportPath build/ -exportOptionsPlist ../ExportOptions.plist

    # Define the artifacts to be saved
    # artifacts:
    #   - ios/App/build/App.ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - camille.ciriaco@gmail.com
       #   - user_2@example.com
        notify:
          success: true
          failure: false
      # app_store_connect:
      #   auth: integration

        # Configuration related to TestFlight (optional)
        # Note: This action is performed during post-processing.
       # submit_to_testflight: true
       

        # Configuration related to App Store (optional)
        # Note: This action is performed during post-processing.
      